### ISSUE TITLE
lib/src/structs.dart:614:7: Error: Field 'hPhysicalMonitor' should be initialized because its type 'int' doesn't allow null.

### ISSUE THREAD

**Issue by chen412115** [timsneath/win32#138]
dart version 
 2.12.0-205.0.dev
When I run example ,shows below

lib/src/structs.dart:614:7: Error: Field 'hPhysicalMonitor' should be initialized because its type 'int' doesn't allow null.
  int hPhysicalMonitor;
      ^^^^^^^^^^^^^^^^
lib/src/structs.dart:3011:7: Error: Field 'Internal' should be initialized because its type 'int' doesn't allow null.
  int Internal;
      ^^^^^^^^
lib/src/structs.dart:3014:7: Error: Field 'InternalHigh' should be initialized because its type 'int' doesn't allow null.
  int InternalHigh;
      ^^^^^^^^^^^^
lib/src/structs.dart:3016:11: Error: Field 'pointer' should be initialized because its type 'Pointer<NativeType>' doesn't allow null.
 - 'Pointer' is from 'dart:ffi'.
 - 'NativeType' is from 'dart:ffi'.
  Pointer pointer;
          ^^^^^^^
lib/src/structs.dart:3019:7: Error: Field 'hEvent' should be initialized because its type 'int' doesn't allow null.
  int hEvent;
      ^^^^^^

**Comment by ilopX** [comment]
Temporary solution 

![image](https://user-images.githubusercontent.com/8049534/104496066-2879b700-55e1-11eb-906f-6bd53dcc68c6.png)

**Comment by timsneath** [comment]
Yeah, thanks -- that's a regression that I hadn't tested for. Should be fixed now.
