### ISSUE TITLE
WriteProcessMemory function does not work

### ISSUE THREAD

**Issue by kirill-21** [timsneath/win32#238]
```
int lpBaseAddress = 0x1;
int value = 1;
int handle = OpenProcess(0x001F0FFF, 0, 17080); //(0x001F0FFF = all access flag)
print(handle); // = 1880
int result = WriteProcessMemory(handle, Pointer<Int32>.fromAddress(lpBaseAddress), Pointer<Int32>.fromAddress(value), sizeOf<Int32>(), nullptr);
print(result); // = 0
```
The result is always 0, program is launched with admin rights. Maybe the problem is that lpBaseAddress is a Pointer, because in Java JNA i had a similar issue with this function and as soon as i've changed it to an integer(in Java JNA, not in Dart), the issue disappeared. It's hard to say that previously described thing will help here, because i don't know what is exactly wrong due to GetLastError() also returns 0 because of https://github.com/dart-lang/sdk/issues/38832

Maybe it's me who's doing something wrong or there's an issue with lpBaseAddress being a Pointer?

**Comment by timsneath** [comment]
Yeah, this isn't `WriteProcessMemory` not working, it's your code, I'm afraid.

`Pointer<Int32>.fromAddress(value)` returns a pointer to the address 0x00000001, not the location in memory of `value`. You'd need to do something more like:

```dart
final buffer = calloc<Uint32>(4);
buffer.value = 0x01;
```

which will allocate a four byte buffer and set its value to 1. 

There may be other errors in your code also, but that was the immediate indication.

The `win32` package is a fairly lightweight wrapper around the Win32 API, based on a generator that works with thousands of APIs; that code is relatively stable at this point.

**Comment by kirill-21** [comment]
> Yeah, this isn't `WriteProcessMemory` not working, it's your code, I'm afraid.
```
final buffer = calloc<Uint32>(sizeOf<Uint32>());
buffer.value = 0x1;

int handle = OpenProcess(0x001F0FFF, 0, 7408); //(0x001F0FFF = all access flag)

int r = WriteProcessMemory(
  activeHandle,
  Pointer<Uint32>.fromAddress(lpBaseAddress),
  buffer,
  sizeOf<Uint32>(),
  nullptr,
);
print(r);
```
Unfortunately, that did not help
