### ISSUE TITLE
Web support to the flutter project in /explorer throws exception

### ISSUE THREAD

**Issue by Maheswari01A** [timsneath/win32#26]
I use Windows 10 Laptop.

C:\Flutter\GitRepos\win32\example\explorer>flutter run -d chrome
Launching lib\main.dart on Chrome in debug mode...
Syncing files to device Chrome...
Unhandled exception:
InvalidType doesn't have nullability
#0      InvalidType.nullability (package:kernel/ast.dart:6709:34)
#1      _CacheTable._typeString (package:dev_compiler/src/kernel/type_table.dart:71:28)
#2      _CacheTable._typeString (package:dev_compiler/src/kernel/type_table.dart:90:19)
#3      _CacheTable.chooseTypeName (package:dev_compiler/src/kernel/type_table.dart:114:31)
#4      _GeneratorTable._nameType (package:dev_compiler/src/kernel/type_table.dart:147:29)
#5      TypeTable.nameFunctionType (package:dev_compiler/src/kernel/type_table.dart:219:28)
#6      ProgramCompiler.visitFunctionType (package:dev_compiler/src/kernel/compiler.dart:2784:22)
#7      ProgramCompiler._emitFunctionTagged (package:dev_compiler/src/kernel/compiler.dart:2457:19)
#8      ProgramCompiler._emitStaticGet (package:dev_compiler/src/kernel/compiler.dart:4197:14)
#9      ProgramCompiler.visitTearOffConstant (package:dev_compiler/src/kernel/compiler.dart:5712:12)
#10     _ConstantCallbackVisitor.visitTearOffConstant (package:kernel/visitor.dart:364:17)
#11     TearOffConstant.accept (package:kernel/ast.dart:8342:42)
#12     ComputeOnceConstantVisitor.visitConstant (package:kernel/visitor.dart:426:52)
#13     ProgramCompiler.visitConstant (package:dev_compiler/src/kernel/compiler.dart:5597:25)
#14     ProgramCompiler._visitExpression (package:dev_compiler/src/kernel/compiler.dart:3329:14)
#15     ProgramCompiler._visitInitializer (package:dev_compiler/src/kernel/compiler.dart:1536:11)
#16     ProgramCompiler._emitStaticFieldInitializer.<anonymous closure> (package:dev_compiler/src/kernel/compiler.dart:2086:23)
#17     ProgramCompiler._withLetScope (package:dev_compiler/src/kernel/compiler.dart:2096:25)
#18     ProgramCompiler._emitStaticFieldInitializer (package:dev_compiler/src/kernel/compiler.dart:2084:40)
#19     ProgramCompiler._emitLazyFields (package:dev_compiler/src/kernel/compiler.dart:2059:43)
#20     ProgramCompiler._emitTopLevelFields (package:dev_compiler/src/kernel/compiler.dart:2044:21)
#21     ProgramCompiler._emitLibrary (package:dev_compiler/src/kernel/compiler.dart:461:7)
#22     List.forEach (dart:core-patch/growable_array.dart:282:8)
#23     ProgramCompiler.emitModule (package:dev_compiler/src/kernel/compiler.dart:345:15)
#24     JavaScriptBundler.compile (package:frontend_server/src/javascript_bundle.dart:133:33)
<asynchronous suspension>
#25     FrontendCompiler.writeJavascriptBundle (package:frontend_server/frontend_server.dart:627:20)
<asynchronous suspension>
#26     FrontendCompiler.compile (package:frontend_server/frontend_server.dart:533:15)
<asynchronous suspension>
#27     _FlutterFrontendCompiler.compile (package:flutter_frontend_server/server.dart:40:22)
#28     listenAndCompile.<anonymous closure> (package:frontend_server/frontend_server.dart:1164:26)
#29     _RootZone.runUnaryGuarded (dart:async/zone.dart:1374:10)
#30     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#31     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)
#32     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:70:11)
#33     _EventSinkWrapper.add (dart:async/stream_transformers.dart:17:11)
#34     _StringAdapterSink.add (dart:convert/string_conversion.dart:238:11)
#35     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:152:13)
#36     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:127:5)
#37     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:165:5)
#38     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:122:24)
#39     _RootZone.runUnaryGuarded (dart:async/zone.dart:1374:10)
#40     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#41     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)
#42     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:70:11)
#43     _EventSinkWrapper.add (dart:async/stream_transformers.dart:17:11)
#44     _StringAdapterSink.add (dart:convert/string_conversion.dart:238:11)
#45     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:243:7)
#46     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:315:20)
#47     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:308:5)
#48     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:74:18)
#49     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:122:24)
#50     _RootZone.runUnaryGuarded (dart:async/zone.dart:1374:10)
#51     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#52     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)
#53     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:779:19)
#54     _StreamController._add (dart:async/stream_controller.dart:655:7)
#55     _StreamController.add (dart:async/stream_controller.dart:597:5)
#56     _Socket._onData (dart:io-patch/socket_patch.dart:1999:41)
#57     _RootZone.runUnaryGuarded (dart:async/zone.dart:1374:10)
#58     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
the Dart compiler exited unexpectedly.
Syncing files to device Chrome...                                4,880ms (!)
Failed to compile application.
#59     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)
#60     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:779:19)
#61     _StreamController._add (dart:async/stream_controller.dart:655:7)
#62     _StreamController.add (dart:async/stream_controller.dart:597:5)
#63     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1544:33)
#64     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1036:14)
#65     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#66     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#67     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#68     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)

C:\Flutter\GitRepos\win32\example\explorer>

**Comment by timsneath** [comment]
Hi there! 

This is by design. This package is not intended to run on the web. The Flutter example here calls a Win32 API to enumerate disk volumes.
