### ISSUE TITLE
Help - A type problem

### ISSUE THREAD

**Issue by koharubiyori** [timsneath/win32#935]
Hello, I'm trying to get windows using win32, but I keep getting a type error: `The type 'BOOL Function(HWND, LPARAM)' must be a subtype of 'WNDENUMPROC' for 'NativeCallable'. Try changing one or both of the type arguments.` in `NativeCallable<WNDENUMPROC>.isolateLocal(test2)` .
How to fix it?

``` dart
void test1(WNDENUMPROC arg) {}
BOOL test2(HWND hwnd, LPARAM lParam) { return TRUE as Uint32; }
  
test1(test2);  // passed
NativeCallable<WNDENUMPROC>.isolateLocal(test2); // dart(must_be_a_subtype) occurred, why?
```

**Comment by halildurmus** [comment]
You need to replace the native types in your `test2` function with Dart types. Here's the updated code:

```diff
- BOOL test2(HWND hwnd, LPARAM lParam) { return TRUE as Uint32; }
+ int test2(int hwnd, int lParam) { return TRUE; }
```

Also, there's an example of calling the same callback in the repository: [examples/window.dart](https://github.com/halildurmus/win32/blob/main/examples/window.dart)

If you haven't already, I recommend reading the [callbacks documentation](https://win32.pub/docs/guides-concepts/callbacks) for a better understanding.
